apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: matrix-user
  labels:
    app: matrix-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-user
  template:
    metadata:
      name: matrix-user
      labels:
        app: matrix-user
    spec:
      #      serviceAccountName: matrix-user-service-account
      restartPolicy: Always
      imagePullSecrets:
        - name: aliyuncs
      containers:
        - name: matrix-user
          image: registry.cn-hangzhou.aliyuncs.com/shishaodong/spring-matrix-user-center:0.0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Xms100M -Xmx100M -Xss256k -XX:+AlwaysPreTouch -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=50M -XX:MaxDirectMemorySize=100M'
            - name: BPL_JVM_THREAD_COUNT
              value: '20'
          envFrom:
            - secretRef:
                name: matrix-user-secret
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 500Mi
          readinessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/readiness
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/liveness
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: matrix-user-config
              mountPath: /workspace/config
            - name: matrix-user-log
              mountPath: /workspace/log
      volumes:
        - name: matrix-user-config
          configMap:
            name: matrix-user-configmap
        - name: matrix-user-log
          persistentVolumeClaim:
            claimName: matrix-user-volume-claim
