apiVersion: v1
kind: PersistentVolume
metadata:
  name: matrix-user-volume
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /apprun/kubelog
    server: 192.168.31.40
#  persistentVolumeReclaimPolicy: Retain
#  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: matrix
  name: matrix-user-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
#  volumeMode: Filesystem
#  volumeName: ministore-volume
