apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: matrix-user
  labels:
    app: matrix-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-user
  template:
    metadata:
      name: matrix-user
      labels:
        app: matrix-user
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aliyuncs
      containers:
        - name: matrix-user
          image: registry.cn-hangzhou.aliyuncs.com/shishaodong/spring-matrix-user-center:0.0.6-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Xms200M -Xmx200M -Xss512k -XX:+AlwaysPreTouch -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=50M -XX:MaxDirectMemorySize=50M'
          resources:
            limits:
              cpu: 2000m
              memory: 500Mi
            requests:
              cpu: 1000m
              memory: 200Mi
          readinessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/readiness
              scheme: HTTP
            initialDelaySeconds: 900
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/liveness
              scheme: HTTP
            initialDelaySeconds: 900
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /workspace/config
              name: matrix-user-configmap
      volumes:
        - name: matrix-user-configmap
          configMap:
            name: matrix-user-configmap

