apiVersion: v1
kind: Service
metadata:
  name: matrix-user-service
  labels:
    app: matrix-user-service
spec:
  selector:
    app: matrix-user-service
  ports:
    - port: 80
      targetPort: 8088
  type: NodePort
