apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: matrix
  name: matrix-user-service-account
  labels:
    app: matrix-user-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: matrix
  name: matrix-user-role
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "list","watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: matrix
  name: matrix-user-RoleBinding
subjects:
  - kind: ServiceAccount
    name: matrix-user-service-account
    namespace: matrix
    apiGroup: ""
roleRef:
  kind: Role
  name: matrix-user-role
  apiGroup: ""
